### ISSUE TITLE
Getting error while running module job

### ISSUE THREAD

**Issue by manishgoyaler** [pascalgrimaud/generator-jhipster-docker#14]
Here is log 

Please let me know if more details are required. 
Here is sample app https://github.com/manishgoyaler/jhipster_sample.git

? Please choose what you want to do: Generate files for Automated build at https://hub.docker.com/
? Choose the version of MySQL: 5.7.9 (default)
? Choose the version of ElasticSearch: 1.7.3 (default)
? GitHub: choose the repository? https://github.com/manishgoyaler/jhipster_sample.git
? Docker Hub: what is your username? manishgoyaler
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /usr/local/lib/node_modules/generator-jhipster-docker/generators/app/templates/_run.sh:63
    61|   JHIPSTER_SLEEP=20
    62| fi

> > 63| <%_ if (dockerTypeImage == 'tomcat' || dockerTypeImage == 'wildfly') { _%>
> >     64| ################################################################################
> >     65| # Start Application Server
> >     66| ################################################################################

dockerTypeImage is not defined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/ejs/lib/ejs.js:464:12), <anonymous>:35:12)
    at returnedFn (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/ejs/lib/ejs.js:493:17)
    at Object.exports.render (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/ejs/lib/ejs.js:315:37)
    at copy.process (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/mem-fs-editor/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/mem-fs-editor/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl](/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/mem-fs-editor/actions/copy-tpl.js:12:8)
    at template (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at module.exports.yeoman.generators.Base.extend.writing (/usr/local/lib/node_modules/generator-jhipster-docker/generators/app/index.js:376:12)

**Comment by pascalgrimaud** [comment]
Thanks for reporting this @manishgoyaler 
I will fix and release a new version asap

I should write npm test...

**Comment by pascalgrimaud** [comment]
New release => v0.0.13
