### ISSUE TITLE
Error Running yo jhipster-docker

### ISSUE THREAD

**Issue by hepaestus** [pascalgrimaud/generator-jhipster-docker#32]
Right out of the box it throws an error. I updated to the latest yo as well.
Thanks
Pete.

```
  (master) $ yo jhipster-docker
 events.js:174
      throw er; // Unhandled 'error' event
      ^
```

 ```
TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/usr/local/lib/node_modules/generator-jhipster-docker/generators/app/index.js:18:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/generator-jhipster-docker/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-docker/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
pete@Medussa:~/git/jhipster-flutter-pizza-store/pizza_store_jh (master) $ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator
```

##### **JHipster Version(s)**

pizza-store@0.0.1-SNAPSHOT /home/pete/git/jhipster-flutter-pizza-store/pizza_store_jh
├── generator-jhipster@6.5.1 
├─┬ generator-jhipster-kutilang@0.0.9
│ └── generator-jhipster@6.5.1  deduped
├─┬ generator-jhipster-paypal@1.0.5
│ └── generator-jhipster@6.5.1  deduped
├─┬ generator-jhipster-social-login-api@0.0.1
│ └── generator-jhipster@6.5.1  deduped
└─┬ generator-jhipster-stripe-payment@1.0.9
  └── generator-jhipster@6.5.1  deduped

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "hepaestus.com"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "pizza_store",
    "packageName": "hepaestus.com",
    "packageFolder": "hepaestus/com",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "SECRET",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "darkly",
    "clientThemeVariant": "dark",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-stripe-payment",
        "version": "1.0.9"
      },
      {
        "name": "generator-jhipster-paypal",
        "version": "1.0.5"
      },
      {
        "name": "generator-jhipster-kutilang",
        "version": "0.0.9"
      },
      {
        "name": "generator-jhipster-social-login-api",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": false,
    "blueprints": [],
    "gcpProjectId": "ody-offer-letter",
    "gaeServiceName": "pizza-store",
    "gaeLocation": "us-east4",
    "gaeInstanceClass": "F2",
    "gaeScalingType": "automatic",
    "gaeMinInstances": "1",
    "gaeMaxInstances": "1",
    "gaeCloudSQLInstanceNeeded": "N",
    "gcpCloudSqlInstanceName": "ody-offer-letter:us-east4:offer-letter-sql",
    "gcpCloudSqlUserName": "pizzaAdmin",
    "gcpCloudSqlDatabaseName": "pizza_store"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Customer {
  name String,
  price BigDecimal required,
  description String,
  image ImageBlob
}
entity Invoice {
  phone String,
  orderplaced LocalDate
}
entity Pizza {
  name String,
  description String,
  price BigDecimal required min(0),
  image ImageBlob,
  size Size required
}
entity Toppings {
  name String required,
  description String,
  price BigDecimal required min(0)
}
enum Size {
  S,
  M,
  L,
  XL,
  XXL
}

relationship OneToMany {
  Invoice{pizza} to Pizza{invoice},
  Pizza{toppings} to Toppings{pizza}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.1, mixed mode, sharing)

git version 2.20.1

node: v10.16.0

npm: 6.11.3

yeoman: 3.1.1

yarn: 1.15.2

Docker version 19.03.2, build 6a30dfca03

docker-compose version 1.23.2, build unknown

INFO! Congratulations, JHipster execution is complete!

``

**Comment by hepaestus** [comment]
```
$ yo
? 'Allo Pete! What would you like to do? Jhipster Docker

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo jhipster-docker


     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/usr/local/lib/node_modules/generator-jhipster-docker/generators/app/index.js:18:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/generator-jhipster-docker/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-docker/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/generator-jhipster-docker/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Seems like it cannot find the jhipster project

**Comment by Oluwatemilorun** [comment]
Also having this issue running `yo jhipster-docker`
```
TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/Users/usr/.config/yarn/global/node_modules/generator-jhipster-docker/generators/app/index.js:18:47)
    at Object.<anonymous> (/Users/usr/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:976:25)
    at /Users/usr/.config/yarn/global/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/usr/.config/yarn/global/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/usr/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:977:11)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

Found a solution that said to replace `this.jhipsterAppConfig = this.getJhipsterAppConfig();` to `this.jhipsterAppConfig = this.getAllJhipsterAppConfig();` But that did not work as well

**Comment by pascalgrimaud** [comment]
Thanks, I need to find time to update this module...
